#!/usr/bin/env bash
# Configure le fichier hosts (IP locale et facebook)

# Remplacement de l'IP (sans sudo car lancé en root)
sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Ajout de facebook (redirection simple avec >>)
echo "8.8.8.8 facebook.com" >> /etc/hosts